services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: 'postgresql://admin:test123@db:5432/chatapp'
    depends_on:
      - db
    networks:
      - chatapp-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: chatapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatapp-network

networks:
  chatapp-network:
    driver: bridge

volumes:
  postgres_data:
